// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Adicionar_maquina_lavar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Adicionar_maquina_lavar', async function() {
    // Test name: Adicionar_maquina_lavar
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5500/App/login/login.html | 
    await driver.get("http://127.0.0.1:5500/App/login/login.html")
    // 2 | setWindowSize | 1319x816 | 
    await driver.manage().window().setRect({ width: 1319, height: 816 })
    // 3 | click | css=.email-form-input | 
    await driver.findElement(By.css(".email-form-input")).click()
    // 4 | click | css=.email-form-input | 
    await driver.findElement(By.css(".email-form-input")).click()
    // 5 | click | css=.email-form-input | 
    await driver.findElement(By.css(".email-form-input")).click()
    // 6 | click | css=.email-form-input > .text-wrapper-3 | 
    await driver.findElement(By.css(".email-form-input > .text-wrapper-3")).click()
    // 7 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 8 | doubleClick | id=email | 
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 9 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 10 | type | id=email | martarepolho233@gmail.com
    await driver.findElement(By.id("email")).sendKeys("martarepolho233@gmail.com")
    // 11 | click | css=.password-form-input | 
    await driver.findElement(By.css(".password-form-input")).click()
    // 12 | click | css=.password-form-input | 
    await driver.findElement(By.css(".password-form-input")).click()
    // 13 | doubleClick | css=.password-form-input | 
    {
      const element = await driver.findElement(By.css(".password-form-input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 14 | click | css=.password-form-input | 
    await driver.findElement(By.css(".password-form-input")).click()
    // 15 | click | css=.password-form-input | 
    await driver.findElement(By.css(".password-form-input")).click()
    // 16 | doubleClick | css=.password-form-input | 
    {
      const element = await driver.findElement(By.css(".password-form-input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 17 | click | css=.password-form-input | 
    await driver.findElement(By.css(".password-form-input")).click()
    // 18 | click | css=.rectangle | 
    await driver.findElement(By.css(".rectangle")).click()
    // 19 | click | css=.password-form-input > .text-wrapper-3 | 
    await driver.findElement(By.css(".password-form-input > .text-wrapper-3")).click()
    // 20 | type | id=password | martarepolho233
    await driver.findElement(By.id("password")).sendKeys("martarepolho233")
    // 21 | click | id=login-button | 
    await driver.findElement(By.id("login-button")).click()
    // 22 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 23 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 24 | doubleClick | id=password | 
    {
      const element = await driver.findElement(By.id("password"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 25 | type | id=password | martinha233
    await driver.findElement(By.id("password")).sendKeys("martinha233")
    // 26 | sendKeys | id=password | ${KEY_ENTER}
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    // 27 | click | id=login-button | 
    await driver.findElement(By.id("login-button")).click()
    // 28 | click | css=.overlap-group-2:nth-child(2) > .img | 
    await driver.findElement(By.css(".overlap-group-2:nth-child(2) > .img")).click()
    // 29 | click | css=.scanner-button | 
    await driver.findElement(By.css(".scanner-button")).click()
    // 30 | click | css=.round-button | 
    await driver.findElement(By.css(".round-button")).click()
    // 31 | click | css=.overlap-group-3 | 
    await driver.findElement(By.css(".overlap-group-3")).click()
    // 32 | click | css=.frame-button | 
    await driver.findElement(By.css(".frame-button")).click()
  })
})
