// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Colocar_duvida_administrador', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Colocar_duvida_administrador', async function() {
    // Test name: Colocar_duvida_administrador
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5500/App/Homepage/homepage.html | 
    await driver.get("http://127.0.0.1:5500/App/Homepage/homepage.html")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // 3 | click | css=.frame-4 > .img-2:nth-child(2) | 
    await driver.findElement(By.css(".frame-4 > .img-2:nth-child(2)")).click()
    // 4 | click | css=.rectangle-2 | 
    await driver.findElement(By.css(".rectangle-2")).click()
    // 5 | type | css=.rectangle-2 | Boa tarde, tenho uma duvida em relaçao aos custos deste mes
    await driver.findElement(By.css(".rectangle-2")).sendKeys("Boa tarde, tenho uma duvida em relaçao aos custos deste mes")
    // 6 | click | css=.text-wrapper | 
    await driver.findElement(By.css(".text-wrapper")).click()
  })
})
